In [4]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
df = pd.read_csv('iris.csv')

display(df)

     sepal.length  sepal.width  petal.length  petal.width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
print(df.values[:, 0])
print(df.values[5:11, :])
print(df.values[1, 4])

[5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.0 5.0 5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.0
 5.5 4.9 4.4 5.1 5.0 4.5 4.4 5.0 5.1 4.8 5.1 4.6 5.3 5.0 7.0 6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.0 5.9 6.0 6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.0 5.7 5.5 5.5 5.8 6.0 5.4 6.0 6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.0 5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.0 6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.0 6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
[[5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']]
setosa

In [7]:
(train_set, test_set) = train_test_split(
    df.values, train_size=0.7, random_state=13)

In [8]:
print(test_set)
print(test_set.shape[0])

[[5.7 2.8 4.5 1.3 'versicolor']
 [5.6 2.9 3.6 1.3 'versicolor']
 [5.1 3.7 1.5 0.4 'setosa']
 [5.8 2.7 5.1 1.9 'virginica']
 [6.8 3.0 5.5 2.1 'virginica']
 [5.5 4.2 1.4 0.2 'setosa']
 [7.7 3.0 6.1 2.3 'virginica']
 [6.3 2.7 4.9 1.8 'virginica']
 [5.1 3.8 1.6 0.2 'setosa']
 [5.5 2.6 4.4 1.2 'versicolor']
 [6.0 3.0 4.8 1.8 'virginica']
 [6.3 2.8 5.1 1.5 'virginica']
 [6.3 2.3 4.4 1.3 'versicolor']
 [5.1 3.8 1.9 0.4 'setosa']
 [5.8 2.8 5.1 2.4 'virginica']
 [4.8 3.1 1.6 0.2 'setosa']
 [6.1 3.0 4.9 1.8 'virginica']
 [6.5 3.0 5.8 2.2 'virginica']
 [6.1 3.0 4.6 1.4 'versicolor']
 [4.4 2.9 1.4 0.2 'setosa']
 [6.0 2.9 4.5 1.5 'versicolor']
 [5.7 4.4 1.5 0.4 'setosa']
 [5.1 3.5 1.4 0.3 'setosa']
 [7.4 2.8 6.1 1.9 'virginica']
 [5.4 3.0 4.5 1.5 'versicolor']
 [6.7 3.3 5.7 2.5 'virginica']
 [5.8 4.0 1.2 0.2 'setosa']
 [7.7 2.6 6.9 2.3 'virginica']
 [6.1 2.9 4.7 1.4 'versicolor']
 [6.4 2.8 5.6 2.2 'virginica']
 [6.4 3.1 5.5 1.8 'virginica']
 [5.2 4.1 1.5 0.1 'setosa']
 [5.4 3.4 1.5 0.4 'setosa']
 [6.9 3.1 5.1 2.3 'virginica']
 [6.3 2.5 5.0 1.9 'virginica']
 [6.2 2.9 4.3 1.3 'versicolor']
 [5.1 3.3 1.7 0.5 'setosa']
 [5.6 3.0 4.5 1.5 'versicolor']
 [6.2 2.2 4.5 1.5 'versicolor']
 [4.8 3.0 1.4 0.1 'setosa']
 [5.2 3.5 1.5 0.2 'setosa']
 [6.1 2.6 5.6 1.4 'virginica']
 [5.7 2.9 4.2 1.3 'versicolor']
 [7.2 3.2 6.0 1.8 'virginica']
 [6.5 3.2 5.1 2.0 'virginica']]
45

In [ ]:
train_inputs = train_set[:, 0:4]
train_classes = train_set[:, 4]
test_inputs = test_set[:, 0:4]
test_classes = test_set[:, 4]